package controller

// Error codes used by controllers. They are put in constants to provide stability in the metrics
// generated by controller components.

const (
	errCreateMesh           = "create_mesh"
	errCreateVirtualNode    = "create_virtual_node"
	errCreateVirtualRouter  = "create_virtual_router"
	errCreateVirtualService = "create_virtual_service"
	errDeleteMesh           = "delete_mesh"
	errDeleteVirtualNode    = "delete_virtual_node"
	errDeleteVirtualService = "delete_virtual_service"
	errDeregisterInstance   = "deregister_instance"
	errGetMesh              = "get_mesh"
	errGetPod               = "get_pod"
	errGetVirtualNode       = "get_virtual_node"
	errGetVirtualRouter     = "get_virtual_router"
	errGetVirtualService    = "get_virtual_service"
	errInvalidSpec          = "invalid_spec"
	errListInstances        = "list_instances"
	errListRoutes           = "list_routes"
	errMeshInactive         = "mesh_not_active"
	errMeshNotFound         = "mesh_not_found"
	errRegisterInstance     = "register_instance"
	errServiceDiscovery     = "service_discovery"
	errUpdateMesh           = "update_mesh"
	errUpdateRoute          = "update_route"
	errUpdateStatus         = "update_status"
	errUpdateVirtualNode    = "update_virtual_node"
	errUpdateVirtualRouter  = "update_virtual_router"
	errUpdateVirtualService = "update_virtual_service"
)
